<a href="https://colab.research.google.com/github/LuisMedinaBravo/IA_Lab1/blob/main/Poker_Hand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Proyecto Inteligencia Artificial**

***Dataset: Poker Hand***

In [ ]:
#importe de bibliotecas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams

rcParams['figure.figsize'] = 10,7
np.random.seed(0)

features = ['S1', 'C1', 'S2', 'C2', 'S3', 'C3', 'S4', 'C4', 'S5', 'C5', 'CLASS']
data = pd.read_csv('https://raw.githubusercontent.com/LuisMedinaBravo/IA_Lab1/main/poker-hand-testing.data', names=features)

# Eliminar valores nulos, si es que existen
data = data.dropna()

#Ordenar de menor a mayor por el atributo "CLASS"
data = data.sort_values(by = ['CLASS'], ignore_index=True)

#mostrar la cabecera del dataset
data.head(10)

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  CLASS
0   1   1   1  13   2   4   2   3   1  12      0
1   3  12   2  13   3   8   2  11   3   4      0
2   2   5   4   7   2  12   4   3   3   2      0
3   3   4   1   5   3  13   2   8   1  10      0
4   2   8   1   9   3   7   4  12   3  10      0
5   1   2   1   4   3   1   4  11   3   9      0
6   2   5   3  13   2   1   3   2   4   7      0
7   3   2   1   1   3  11   2  12   4   7      0
8   4  11   4   7   3  13   4   8   1   6      0
9   1  10   4   7   1  11   3   8   1   5      0

In [ ]:
#Verificar si quedaron valores nulos
data.notna()

S1    C1    S2    C2    S3    C3    S4    C4    S5    C5  CLASS
0       True  True  True  True  True  True  True  True  True  True   True
1       True  True  True  True  True  True  True  True  True  True   True
2       True  True  True  True  True  True  True  True  True  True   True
3       True  True  True  True  True  True  True  True  True  True   True
4       True  True  True  True  True  True  True  True  True  True   True
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
999995  True  True  True  True  True  True  True  True  True  True   True
999996  True  True  True  True  True  True  True  True  True  True   True
999997  True  True  True  True  True  True  True  True  True  True   True
999998  True  True  True  True  True  True  True  True  True  True   True
999999  True  True  True  True  True  True  True  True  True  True   True

[1000000 rows x 11 columns]

In [ ]:
#(números de filas, número de columnas) 
data.shape

(1000000, 11)

In [ ]:
#tamaño dataset (número de filas por número de columnas)
data.size

11000000

In [ ]:
#quitar filas duplicadas
data = np.unique(data,axis=0)
#uniques.size

data.size

10976592

In [ ]:

nb_classes = 10  # we have 10 classes of poker hands
cls = {}
for i in range(nb_classes):
    cls[i] = len(data[data.CLASS==i])
    
poker_hands = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
hand_name = {
    0: 'Nothing in hand',
    1: 'One pair',
    2: 'Two pairs',
    3: 'Three of a kind',
    4: 'Straight',
    5: 'Flush',
    6: 'Full house',
    7: 'Four of a kind',
    8: 'Straight flush',
    9: 'Royal flush',
}

for i in poker_hands:
    print("%s: %d" % (hand_name[i], cls[i]))

AttributeError: ignored

In [ ]:
# preparacion de datos

df = pd.DataFrame(data,columns=['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5','CLASS']) 
data_values= df[['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5']]

data_target= df[['CLASS']]

x= data_values
y= data_target

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y,train_size=0.80 , test_size=0.20,shuffle = True)

print('x_train: ',x_train.shape)
print('x_test: ',x_test.shape)
print('y_train: ',y_train.shape)
print('y_test: ',y_test.shape)

print('y:', data_values.shape, data_target.shape)


x_train:  (798297, 10)
x_test:  (199575, 10)
y_train:  (798297, 1)
y_test:  (199575, 1)
y: (997872, 10) (997872, 1)


In [ ]:
#arboles de desicion
#importamos el algoritmo a utilizar
from sklearn.tree import DecisionTreeClassifier

alg= DecisionTreeClassifier();

#entreno el modelo
alg.fit(x_train,y_train)

#realizamos prediccion
y_pred= alg.predict(x_test)

#comprobacion y_pred
print('y_pred: ',y_pred.size)
print(y_pred[1:10])

y_pred:  199575
[0 1 0 0 0 1 2 0 0]


In [ ]:
#matriz de confusion (que tan acertado es la prediccion)
from sklearn.metrics import confusion_matrix
matriz= confusion_matrix(y_test, y_pred)
#los datos de la diagonal son los datos acertados
print("Matriz confusion: ")
print(matriz)

diagonal= 0;
suma=0;
for columna in range(len(matriz[0])):
        for fila in range(len(matriz)):
            if(columna==fila):
                diagonal+=matriz[columna][fila]
            else:
                suma+=matriz[columna][fila]

print()
print('Total: ',diagonal+suma,', Errores: ',suma, ', Aciertos: ',diagonal,', Precision: ',diagonal/(diagonal+suma))


Matriz confusion: 
[[72550 25145  1281   415    70   458    10     0     0     0]
 [24071 51815  5693  2200   488    96    96     6     3     3]
 [  985  4838  3163   325    71     2   116    17     0     0]
 [  292  1808   323  1653    19     1    79    16     0     0]
 [   58   404    75    28   182     0     2     0     1     1]
 [  275    59     1     0     0    59     0     0     0     0]
 [    9    71    97    66     1     0    28     1     0     0]
 [    0     9     7    19     0     0     2     8     0     0]
 [    1     1     0     0     1     0     0     0     0     0]
 [    0     0     0     0     0     1     0     0     0     0]]

Total:  199575 , Errores:  70117 , Aciertos:  129458 , Precision:  0.6486684203933358


In [ ]:
#precision del modelo
from sklearn.metrics import precision_score,accuracy_score
precision= precision_score(y_test, y_pred,average='micro', zero_division=0)
print('Sklearn-average/micro: ',precision)

precision2= accuracy_score(y_test, y_pred)
print('Accuracy: ',precision2)

Sklearn-average/micro:  0.6486684203933358
Accuracy:  0.6486684203933358


KNN Modelo

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
#KNN
knn = KNeighborsClassifier(n_neighbors=10)
# Se entrena el modelo
knn.fit(x_train, np.ravel(y_train,order='C'))

y_pred= knn.predict(x_test)


In [ ]:
#comprobacion y_pred
print('y_pred: ',y_pred.size)
print(y_pred[1:10])


y_pred:  199575
[0 0 0 0 0 1 1 0 1]


In [ ]:
#prediccion knn
print("Matriz de Confusión:\n",confusion_matrix(y_test,y_pred))
print("\nPuntuación de precisión:",accuracy_score(y_test,y_pred))

Matriz de Confusión:
 [[80593 19250    83     3     0     0     0     0     0     0]
 [39509 44475   402    73    12     0     0     0     0     0]
 [ 2514  6469   451    78     4     0     1     0     0     0]
 [  170  3805   130    85     0     0     1     0     0     0]
 [   45   685    13     1     7     0     0     0     0     0]
 [  343    51     0     0     0     0     0     0     0     0]
 [    5   211    48     7     0     0     2     0     0     0]
 [    0    23    16     6     0     0     0     0     0     0]
 [    0     3     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0]]

Puntuación de precisión: 0.629402480270575


**Regresión logística**

In [2]:
#regresion logistica


#Se escalan todos los datos
from sklearn.preprocessing import StandardScaler
escalar = StandardScaler()
x_train = escalar.fit_transform(x_train)
x_test = escalar.transform(x_test)

#se entrena el modelo
from sklearn.linear_model import LogisticRegression

lineal= LogisticRegression(max_iter=800000,multi_class='multinomial',solver ='newton-cg')
#lineal.fit(x_train,y_train)
lineal.fit(x_train, np.ravel(y_train,order='C'))
y_pred= lineal.predict(x_test)


#comprobacion y_pred
print('y_pred: ',y_pred.size)
print(y_pred[1:10])

NameError: ignored

In [1]:
exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

NameError: ignored